-- Create a new database called 'AULA_SQL;'
CREATE DATABASE AULA_SQL;

DROP DATABASE AULA_SQL;

CREATE DATABASE DB_AULA25MAR24;

USE DB_AULA25MAR24;

CREATE TABLE fornecedor(
    Fcodigo INT NOT NULL
    Fnome VARCHAR(30) NOT NULL,
    Status INT,
    Cidade VARCHAR(30)
);

SELECT* FROM fornecedor;